#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# install_glpi_final.sh - instalador automático GLPI (Debian/Ubuntu | RHEL/Rocky)
LOG="/var/log/glpi_install.log"
exec > >(tee -a "$LOG") 2>&1

echo "=============================================="
echo "  Instalador GLPI"
echo "=============================================="

if [ "$EUID" -ne 0 ]; then
  echo "Execute como root (sudo)." >&2
  exit 1
fi

# Detect OS and package manager specifics
if [ -f /etc/debian_version ]; then
  OS="debian"
  WEB_USER="www-data"
  APACHE_SERVICE="apache2"
  REDIS_SERVICE="redis-server"
  PKG_UPDATE_CMD=("apt" "update")
  PKG_UPGRADE_CMD=("apt" "upgrade" "-y")
  PKG_INSTALL_CMD=("apt" "install" "-y")
elif [ -f /etc/redhat-release ]; then
  OS="rhel"
  WEB_USER="apache"
  # prefer dnf if available
  if command -v dnf >/dev/null 2>&1; then
    PM="dnf"
  else
    PM="yum"
  fi
  APACHE_SERVICE="httpd"
  REDIS_SERVICE="redis"
  PKG_UPDATE_CMD=("$PM" "-y" "update")
  PKG_UPGRADE_CMD=("$PM" "-y" "upgrade")
  PKG_INSTALL_CMD=("$PM" "install" "-y")
else
  echo "Sistema não suportado por este instalador." >&2
  exit 1
fi

echo "Sistema detectado: $OS"
echo "Log: $LOG"

# Variables
DB_NAME="glpidb"
DB_USER="glpiuser"
DB_PASS="$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 16)"
GLPI_DIR="/var/www/glpi"
TMP_TGZ="/tmp/glpi.tgz"
CRED_FILE="/root/glpi_db_credentials.txt"

echo "Senha gerada para DB: $DB_PASS"

# Helper to run package manager commands (array)
run_cmd() { "$@"; }

# 1) Update & install packages
echo "Atualizando pacotes..."
run_cmd "${PKG_UPDATE_CMD[@]}"

# For Debian, apply upgrade
if [ "$OS" = "debian" ]; then
  run_cmd "${PKG_UPGRADE_CMD[@]}"
fi

echo "Instalando pacotes necessários..."
if [ "$OS" = "debian" ]; then
  # Debian/Ubuntu packages
  run_cmd "${PKG_INSTALL_CMD[@]}" apache2 mariadb-server "$REDIS_SERVICE" curl wget unzip tar \
    php php-cli php-common php-mysql php-xml php-mbstring php-curl php-gd php-intl php-zip php-bz2 php-ldap php-apcu php-redis
else
  # RHEL-based packages
  run_cmd "${PKG_INSTALL_CMD[@]}" epel-release || true
  run_cmd "${PKG_INSTALL_CMD[@]}" "$APACHE_SERVICE" mariadb-server "$REDIS_SERVICE" curl wget unzip tar \
    php php-cli php-common php-mysqlnd php-xml php-mbstring php-curl php-gd php-intl php-zip php-bz2 php-ldap php-pecl-apcu php-pecl-redis || true
fi

# Enable & start services
echo "Ativando serviços: Apache, MariaDB, Redis..."
systemctl enable --now "$APACHE_SERVICE" || true
systemctl enable --now mariadb || true
systemctl enable --now "$REDIS_SERVICE" || true

# 2) Secure MariaDB minimal (non-interactive)
echo "Aplicando hardening básico do MariaDB..."
mysql -u root <<SQL
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
SQL

# 3) Create DB and user (MariaDB compatible: IDENTIFIED BY)
echo "Criando database e usuario (compatível MariaDB)..."
mysql -u root <<SQL
DROP DATABASE IF EXISTS \`${DB_NAME}\`;
DROP USER IF EXISTS '${DB_USER}'@'localhost';
CREATE DATABASE \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

# store credentials securely
cat > "$CRED_FILE" <<EOF
GLPI DB credentials (generated by installer)
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
EOF
chmod 600 "$CRED_FILE"
echo "Credenciais salvas em $CRED_FILE (root only)"

# 4) Download GLPI latest release
echo "Recuperando a última release do GLPI do GitHub..."
GLPI_URL=$(curl -s https://api.github.com/repos/glpi-project/glpi/releases/latest \
  | grep browser_download_url | grep ".tgz" | head -n1 | cut -d '"' -f4)

if [ -z "$GLPI_URL" ]; then
  echo "ERRO: não foi possível obter URL da release do GLPI." >&2
  exit 1
fi
echo "Baixando: $GLPI_URL"
wget -O "$TMP_TGZ" "$GLPI_URL" || { echo "Erro no download do GLPI"; exit 1; }

# 5) Extract & normalize path
echo "Extraindo GLPI em $GLPI_DIR..."
rm -rf "$GLPI_DIR"
mkdir -p /var/www
tar -xzf "$TMP_TGZ" -C /var/www/ || { echo "Erro ao extrair arquivo"; exit 1; }

# If tar extracted into glpi or glpi-x.y.z
if [ -d /var/www/glpi ]; then
  true
else
  FIRST=$(ls -1 /var/www | grep -E '^glpi' | head -n1 || true)
  if [ -n "$FIRST" ]; then
    mv "/var/www/$FIRST" /var/www/glpi
  else
    echo "Erro: não foi encontrada pasta GLPI após extração." >&2
    exit 1
  fi
fi

# 6) Permissions (as GLPI docs)
echo "Ajustando permissões..."
chown -R "${WEB_USER}:${WEB_USER}" "$GLPI_DIR"
find "$GLPI_DIR" -type d -exec chmod 755 {} \;
find "$GLPI_DIR" -type f -exec chmod 644 {} \;
for d in files config files/_log; do
  mkdir -p "$GLPI_DIR/$d"
  chown -R "${WEB_USER}:${WEB_USER}" "$GLPI_DIR/$d"
  chmod -R 775 "$GLPI_DIR/$d"
done

# --- AJUSTE .HTACCESS PARA GLPI 10 ---
echo "Criando .htaccess na pasta public..."
cat > "${GLPI_DIR}/public/.htaccess" <<HTACCESS
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
HTACCESS
chown "${WEB_USER}:${WEB_USER}" "${GLPI_DIR}/public/.htaccess"
# ------------------------------------

# 7) PHP tweaks (php.ini)
echo "Ajustando php.ini (parâmetros mínimos)..."
PHP_INI_PATH=$(php --ini | awk -F': ' '/Loaded Configuration/{print $2}')
if [ -n "$PHP_INI_PATH" ] && [ -f "$PHP_INI_PATH" ]; then
  sed -i "s/^upload_max_filesize.*/upload_max_filesize = 20M/" "$PHP_INI_PATH" || true
  sed -i "s/^post_max_size.*/post_max_size = 20M/" "$PHP_INI_PATH" || true
  sed -i "s/^max_execution_time.*/max_execution_time = 120/" "$PHP_INI_PATH" || true
  sed -i "s/^memory_limit.*/memory_limit = 512M/" "$PHP_INI_PATH" || true
  sed -i "s/^max_input_vars.*/max_input_vars = 5000/" "$PHP_INI_PATH" || true
  sed -i "s@^;*date.timezone.*@date.timezone = \"America/Sao_Paulo\"@" "$PHP_INI_PATH" || true
fi
# reload apache/php-fpm if needed
systemctl reload "$APACHE_SERVICE" 2>/dev/null || true

# 8) Apache VirtualHost (simple) -> DocumentRoot to GLPI public
echo "Configurando VirtualHost Apache..."
HOSTNAME_FQDN=$(hostname -f 2>/dev/null || hostname)
if [ "$OS" = "debian" ]; then
  # create site file (idempotent)
  if [ ! -f /etc/apache2/sites-available/glpi.conf ]; then
    cat > /etc/apache2/sites-available/glpi.conf <<APACHE
<VirtualHost *:80>
    ServerName ${HOSTNAME_FQDN}
    DocumentRoot ${GLPI_DIR}/public
    <Directory ${GLPI_DIR}/public>
        Require all granted
        AllowOverride All
    </Directory>
    ErrorLog \${APACHE_LOG_DIR}/glpi_error.log
    CustomLog \${APACHE_LOG_DIR}/glpi_access.log combined
</VirtualHost>
APACHE
  fi

  # enable rewrite and site
  a2enmod rewrite || true
  a2ensite glpi.conf || true
  a2dissite 000-default.conf || true
  systemctl reload apache2 || true
else
  if [ ! -f /etc/httpd/conf.d/glpi.conf ]; then
    cat > /etc/httpd/conf.d/glpi.conf <<APACHE
<VirtualHost *:80>
    ServerName ${HOSTNAME_FQDN}
    DocumentRoot ${GLPI_DIR}/public
    <Directory ${GLPI_DIR}/public>
        Require all granted
        AllowOverride All
    </Directory>
    ErrorLog /var/log/httpd/glpi_error.log
    CustomLog /var/log/httpd/glpi_access.log combined
</VirtualHost>
APACHE
  fi
  systemctl reload httpd || true
fi

# 9) Install DB via GLPI CLI as web user (with fallback)
echo "Instalando GLPI via CLI (executando como ${WEB_USER})..."
set +e
sudo -u "${WEB_USER}" php "${GLPI_DIR}/bin/console" db:install \
  --db-host=localhost \
  --db-name="${DB_NAME}" \
  --db-user="${DB_USER}" \
  --db-password="${DB_PASS}" \
  --no-interaction
RC=$?
set -e

if [ $RC -ne 0 ]; then
  echo "db:install retornou $RC. Tentando com --allow-superuser..."
  sudo -u "${WEB_USER}" php "${GLPI_DIR}/bin/console" db:install \
    --db-host=localhost \
    --db-name="${DB_NAME}" \
    --db-user="${DB_USER}" \
    --db-password="${DB_PASS}" \
    --allow-superuser \
    --no-interaction || true
fi

# 10) Configure Redis (local_define.php + console fallback)
echo "Configurando Redis no GLPI (local_define.php)..."
LOCAL_DEFINE="${GLPI_DIR}/config/local_define.php"
cat > "$LOCAL_DEFINE" <<PHPDEF
<?php
define('GLPI_CACHE_TYPE', 'redis');
define('GLPI_REDIS_HOST', '127.0.0.1');
define('GLPI_REDIS_PORT', 6379);
define('GLPI_REDIS_DB', 0);
PHPDEF
chown "${WEB_USER}:${WEB_USER}" "$LOCAL_DEFINE"
chmod 644 "$LOCAL_DEFINE"

# Try console config as well
if sudo -u "${WEB_USER}" php "${GLPI_DIR}/bin/console" config:list >/dev/null 2>&1; then
  sudo -u "${WEB_USER}" php "${GLPI_DIR}/bin/console" config:set cache_handler redis || true
  sudo -u "${WEB_USER}" php "${GLPI_DIR}/bin/console" config:set redis_host 127.0.0.1 || true
fi

# 11) Cron: cron.d + systemd timer
echo "Configurando cron (cron.d + systemd timer)..."
CRON_FILE="/etc/cron.d/glpi"
cat > "$CRON_FILE" <<CRON
*/5 * * * * ${WEB_USER} php ${GLPI_DIR}/bin/console glpi:cron >> ${GLPI_DIR}/files/_log/cron.log 2>&1
CRON
chmod 644 "$CRON_FILE"

TIMER_SVC="/etc/systemd/system/glpi-cron.service"
TIMER_TM="/etc/systemd/system/glpi-cron.timer"
cat > "$TIMER_SVC" <<SVC
[Unit]
Description=GLPI Cron Job
After=network.target

[Service]
Type=oneshot
User=${WEB_USER}
ExecStart=/usr/bin/php ${GLPI_DIR}/bin/console glpi:cron
SVC

cat > "$TIMER_TM" <<TIMER
[Unit]
Description=Run GLPI cron every 5 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Unit=glpi-cron.service

[Install]
WantedBy=timers.target
TIMER

systemctl daemon-reload || true
systemctl enable --now glpi-cron.timer || true

# Final
IP=$(hostname -I | awk '{print $1}' | head -n1 || echo "localhost")
echo ""
echo "=============================================="
echo "  INSTALAÇÃO CONCLUÍDA"
echo "  Acesse: http://${IP}/ (GLPI em ${GLPI_DIR}/public)"
echo ""
echo "  DB_NAME: ${DB_NAME}"
echo "  DB_USER: ${DB_USER}"
echo "  DB_PASS: ${DB_PASS}"
echo ""
echo "Credenciais salvas em: ${CRED_FILE}"
echo "Logs: ${LOG}"
echo "=============================================="
