#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# INSTALL_GLPI_FINAL.sh - Instalador automático GLPI (Debian/Ubuntu | RHEL/Rocky)
# Segue recomendações oficiais do GLPI (downstream/local_define, php.ini, timezone, permissões).
# Referência: GLPI Install Tutorial. :contentReference[oaicite:3]{index=3}

LOG="/var/log/glpi_install.log"
exec > >(tee -a "$LOG") 2>&1

echo "=========================================="
echo "  INSTALL_GLPI_FINAL - Instalador GLPI v1"
echo "=========================================="

if [ "$EUID" -ne 0 ]; then
  echo "Execute como root."
  exit 1
fi

# Detect OS
if [ -f /etc/debian_version ]; then
  OS="debian"
  WEB_USER="www-data"
  PKG_UPDATE="apt update -y"
  PKG_INSTALL="apt install -y"
  PHP_PKG_PREFIX="php"
elif [ -f /etc/redhat-release ]; then
  OS="rhel"
  WEB_USER="apache"
  PKG_UPDATE="dnf -y update"
  PKG_INSTALL="dnf install -y"
  PHP_PKG_PREFIX="php"
else
  echo "Sistema não suportado."
  exit 1
fi

echo "Sistema detectado: $OS"
echo "Log: $LOG"

# Variables
DB_NAME="glpidb"
DB_USER="glpiuser"
DB_PASS=$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 16)
GLPI_INSTALL_DIR="/var/www/glpi"
TMP_TGZ="/tmp/glpi.tgz"

echo "Senha gerada para DB: $DB_PASS"

# 1) Atualizar e instalar pacotes (inclui PHP + extensões recomendadas)
echo "Instalando dependências (Apache/MariaDB/PHP/Redis)..."
if [ "$OS" = "debian" ]; then
  $PKG_UPDATE
  # instalar pacote php via sury ppa se desejar versão mais nova (omitir se já estiver configurado)
  # apt install -y software-properties-common && add-apt-repository ppa:ondrej/php -y && apt update -y

  $PKG_INSTALL apache2 mariadb-server redis-server curl wget unzip tar \
    php php-cli php-common php-mysql php-xml php-mbstring php-curl php-gd php-intl php-zip php-bz2 php-ldap php-apcu php-redis
else
  $PKG_UPDATE
  $PKG_INSTALL httpd mariadb-server redis curl wget unzip tar \
    php php-cli php-common php-mysqlnd php-xml php-mbstring php-curl php-gd php-intl php-zip php-bz2 php-ldap php-pecl-apcu php-pecl-redis
fi

# Enable & start services
echo "Ativando serviços..."
if [ "$OS" = "debian" ]; then
  systemctl enable --now apache2 mariadb redis-server
else
  systemctl enable --now httpd mariadb redis
fi

# 2) Secure MariaDB minimal (non-interactive)
echo "Configurando MariaDB (remoção anon, test DB, etc)..."
# Set root auth if needed: *we assume root access via unix_socket or root without password*
mysql -u root <<SQL
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
SQL

# Load timezone info so GLPI can use timezone functions (recomendado)
if command -v mysql_tzinfo_to_sql >/dev/null 2>&1; then
  echo "Carregando timezone info no MySQL..."
  mysql_tzinfo_to_sql /usr/share/zoneinfo 2>/dev/null | mysql mysql || true
fi

# 3) Create DB and user (MariaDB-compatible syntax -> IDENTIFIED BY)
echo "Criando database e usuário (forçando criação limpa)..."
mysql -u root <<SQL
DROP DATABASE IF EXISTS \`${DB_NAME}\`;
DROP USER IF EXISTS '${DB_USER}'@'localhost';
CREATE DATABASE \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

# Save credentials securely
CRED_FILE="/root/glpi_db_credentials.txt"
chmod 600 "$CRED_FILE" 2>/dev/null || true
cat > "$CRED_FILE" <<EOF
GLPI DB credentials (generated by installer)
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
EOF
chmod 600 "$CRED_FILE"

echo "Credenciais salvas em $CRED_FILE"

# 4) Download latest GLPI release from GitHub
echo "Obtendo última versão do GLPI (GitHub releases)..."
GLPI_URL=$(curl -s https://api.github.com/repos/glpi-project/glpi/releases/latest \
  | grep browser_download_url | grep ".tgz" | head -n1 | cut -d '"' -f4)

if [ -z "$GLPI_URL" ]; then
  echo "Erro: não consegui obter GLPI URL via GitHub API."
  exit 1
fi

echo "Baixando: $GLPI_URL"
wget -O "$TMP_TGZ" "$GLPI_URL" || { echo "Erro ao baixar GLPI"; exit 1; }

# 5) Extract and prepare files
echo "Extraindo GLPI em $GLPI_INSTALL_DIR..."
rm -rf "$GLPI_INSTALL_DIR"
mkdir -p "$(dirname "$GLPI_INSTALL_DIR")"
tar -xzf "$TMP_TGZ" -C /var/www/ || { echo "Erro ao extrair"; exit 1; }
# Some tarballs extract to a glpi-X.Y.Z folder; normalize
if [ -d /var/www/glpi ]; then
  true
else
  # move first matching directory starting with glpi- into /var/www/glpi
  FIRST_DIR=$(ls -1 /var/www | grep -E '^glpi' | head -n1)
  if [ -n "$FIRST_DIR" ]; then
    mv "/var/www/$FIRST_DIR" /var/www/glpi
  fi
fi

# Ensure web ownership & permissions
echo "Ajustando permissões (user: $WEB_USER)..."
chown -R "${WEB_USER}:${WEB_USER}" "$GLPI_INSTALL_DIR"
find "$GLPI_INSTALL_DIR" -type d -exec chmod 755 {} \;
find "$GLPI_INSTALL_DIR" -type f -exec chmod 644 {} \;
# writable dirs
for d in files config files/_log; do
  mkdir -p "$GLPI_INSTALL_DIR/$d"
  chown -R "${WEB_USER}:${WEB_USER}" "$GLPI_INSTALL_DIR/$d"
  chmod -R 775 "$GLPI_INSTALL_DIR/$d"
done

# 6) PHP configuration tweaks (php.ini)
echo "Ajustando php.ini (upload_max_filesize, post_max_size, memory_limit, max_execution_time, timezone)..."
PHP_INI="$(php --ini | awk -F': ' '/Loaded Configuration/{print $2}')"
if [ -n "$PHP_INI" ] && [ -f "$PHP_INI" ]; then
  sed -i "s/^upload_max_filesize.*/upload_max_filesize = 20M/" "$PHP_INI" || true
  sed -i "s/^post_max_size.*/post_max_size = 20M/" "$PHP_INI" || true
  sed -i "s/^max_execution_time.*/max_execution_time = 60/" "$PHP_INI" || true
  sed -i "s/^memory_limit.*/memory_limit = 256M/" "$PHP_INI" || true
  sed -i "s/^max_input_vars.*/max_input_vars = 5000/" "$PHP_INI" || true
  sed -i "s@^;*date.timezone.*@date.timezone = \"America/Sao_Paulo\"@" "$PHP_INI" || true
fi

# 7) Apache virtualhost (simple) -> DocumentRoot to GLPI public
echo "Configurando VirtualHost Apache (DocumentRoot -> ${GLPI_INSTALL_DIR}/public)..."
if [ "$OS" = "debian" ]; then
  cat > /etc/apache2/sites-available/glpi.conf <<APACHECONF
<VirtualHost *:80>
    ServerName $(hostname -f 2>/dev/null || _)
    DocumentRoot ${GLPI_INSTALL_DIR}/public
    <Directory ${GLPI_INSTALL_DIR}/public>
        Require all granted
        AllowOverride All
    </Directory>
    ErrorLog \${APACHE_LOG_DIR}/glpi_error.log
    CustomLog \${APACHE_LOG_DIR}/glpi_access.log combined
</VirtualHost>
APACHECONF
  a2enmod rewrite || true
  a2dissite 000-default.conf || true
  a2ensite glpi.conf
  systemctl reload apache2
else
  cat > /etc/httpd/conf.d/glpi.conf <<APACHECONF
<VirtualHost *:80>
    ServerName $(hostname -f 2>/dev/null || _)
    DocumentRoot ${GLPI_INSTALL_DIR}/public
    <Directory ${GLPI_INSTALL_DIR}/public>
        Require all granted
        AllowOverride All
    </Directory>
    ErrorLog /var/log/httpd/glpi_error.log
    CustomLog /var/log/httpd/glpi_access.log combined
</VirtualHost>
APACHECONF
  systemctl reload httpd
fi

# 8) Install DB via GLPI CLI as web user (recommended)
echo "Instalando banco via GLPI CLI (executando como $WEB_USER)..."
set +e
sudo -u "$WEB_USER" php "${GLPI_INSTALL_DIR}/bin/console" db:install \
  --db-host=localhost \
  --db-name="$DB_NAME" \
  --db-user="$DB_USER" \
  --db-password="$DB_PASS" \
  --no-interaction
RC=$?
set -e

if [ $RC -ne 0 ]; then
  echo "Aviso: db:install retornou código $RC. Tentando com --allow-superuser..."
  sudo -u "$WEB_USER" php "${GLPI_INSTALL_DIR}/bin/console" db:install \
    --db-host=localhost \
    --db-name="$DB_NAME" \
    --db-user="$DB_USER" \
    --db-password="$DB_PASS" \
    --allow-superuser \
    --no-interaction
fi

# 9) Configure Redis (cache/session) via console if supported
echo "Configurando Redis (cache) no GLPI (se disponível)..."
if sudo -u "$WEB_USER" php "${GLPI_INSTALL_DIR}/bin/console" config:list >/dev/null 2>&1; then
  sudo -u "$WEB_USER" php "${GLPI_INSTALL_DIR}/bin/console" config:set cache_handler redis || true
  sudo -u "$WEB_USER" php "${GLPI_INSTALL_DIR}/bin/console" config:set redis_host 127.0.0.1 || true
fi

# 10) Cron setup (systemd timer preferred, mas manter compatibilidade com cron.d)
echo "Configurando cron do GLPI (cron.d)..."
CRON_FILE="/etc/cron.d/glpi"
cat > "$CRON_FILE" <<CRON
*/5 * * * * ${WEB_USER} php ${GLPI_INSTALL_DIR}/bin/console glpi:cron >> ${GLPI_INSTALL_DIR}/files/_log/cron.log 2>&1
CRON
chmod 644 "$CRON_FILE"

# Optionally create systemd timer (safer). We'll create both: cron.d and systemd timer.
TIMER_SERVICE="/etc/systemd/system/glpi-cron.service"
TIMER_TIMER="/etc/systemd/system/glpi-cron.timer"
cat > "$TIMER_SERVICE" <<SERV
[Unit]
Description=GLPI Cron Service
After=network.target

[Service]
Type=oneshot
User=${WEB_USER}
ExecStart=/usr/bin/php ${GLPI_INSTALL_DIR}/bin/console glpi:cron
SERV

cat > "$TIMER_TIMER" <<TIMER
[Unit]
Description=Run GLPI cron every 5 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Unit=glpi-cron.service

[Install]
WantedBy=timers.target
TIMER

systemctl daemon-reload || true
systemctl enable --now glpi-cron.timer || true

# 11) Final message
IP=$(hostname -I | awk '{print $1}')
echo ""
echo "=========================================="
echo "  INSTALAÇÃO CONCLUÍDA"
echo "  Acesse: http://${IP}"
echo ""
echo "  GLPI Path: ${GLPI_INSTALL_DIR}"
echo "  DB: ${DB_NAME}"
echo "  DB USER: ${DB_USER}"
echo "  DB PASS: ${DB_PASS}"
echo ""
echo "Verifique logs: $LOG"
echo "=========================================="
